### ISSUE TITLE
Fail to install package

### ISSUE THREAD

**Issue by khalilT** [RS-eco/bdc#2]
Hi,
the package fails to install using remotes::install github, also using devtools.
Do you think it has to do with the R version? I am using the last one R 4.2.0.

`remotes::install_github("RS-eco/bdc", build_vignettes = T)`

`Downloading GitHub repo RS-eco/bdc@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/RS-eco/bdc/tarball/HEAD' failed`

`> sessionInfo()
R version 4.2.0 (2022-04-22)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 21.10`

Thanks !

**Comment by RS-eco** [comment]
Hey,

to me this sounds like you do not have a stable internet connection.
I am also using Ubuntu and the latest Rversion, but do not have any problems.
Alternatively, you can try installing it without the vignettes, by using: build_vignettes = F

**Comment by RS-eco** [comment]
This seems to be a common issue, one way around it is to use an alternative download method:

```{r}
tmp_zip <- tempfile(fileext = ".zip")
source_url <- "https://api.github.com/repos/RS-eco/bavDC/zipball/main"
utils::download.file(source_url, destfile=tmp_zip, method="wget")
file.exists(tmp_zip)

remotes::install_local(tmp_zip)
```

Please note that I have now transfered the package to a new repository (bavDC), as there is a package with the previous name (bdc) available on CRAN.
